### ISSUE TITLE
Substitute for MICROFC-60035-SMT-TR1

### ISSUE THREAD

**Issue by AndreiUlmeyda** [Open-Gamma-Project/Open-Gamma-Detector#12]
Hey there, awesome project!

I managed to buy most of the parts for this project but eventually I realised that the SiMP MICROFC-60035-SMT-TR1 seems to be out of stock everywhere I knew to look (mouser, digikey,etc.).

Do you happen to know a distributor who isnt't out of stock?

Alternatively, are there equivalent SiMPs which are more widely available and which could be integrated into the project with moderate effort?

Thanks in advance,

Adrian

**Comment by Phoenix1747** [comment]
Hi there! Thanks for your interest :)

Unfortunately you're right, it seems like the SiPM is out of stock everywhere since the start of the Ukraine war according to [Octopart](https://octopart.com/microfc-60035-smt-tr1-onsemi-96322254?r=sp#InventoryHistory). Essentially you can use any other SiPM with roughly the similar specifications, the most important being the recommended (over)voltage -- that's why I made the SiPM gain and voltage variable with the new board.

You can look for any other MICROFC SiPM, maybe you still find one as they are all similar in specs, only different in sizes. At the moment, however, I'm mainly looking into the Broadcom AFBR-S4N66C013 which looks very similar to the MICROFC. The inventory looks great for now (thousands currently in stock with quick restocking intervals), but the only disadvantage of it is the BGA packaging.

https://octopart.com/afbr-s4n66c013-broadcom-100964440?r=sp
https://www2.mouser.com/ProductDetail/Broadcom-Avago/AFBR-S4N66C013?qs=T3oQrply3y%252B9kiyudO%2F1CA%3D%3D

I'm always looking for further alternatives, so if somebody has viable suggestions, feel free to reach out. Thanks!

**Comment by AndreiUlmeyda** [comment]
Thanks for the info, I've just ordered one.

I'll keep you posted whether I manage to make it work or not :D

Cheers!

**Comment by Phoenix1747** [comment]
Just to keep you updated here -- there is a new carrier board for the AFBR-S4N66C013 SiPM:

https://github.com/Open-Gamma-Project/AFBR-SiPM-Carrier-Board

At the moment, at least on Mouser there aren't any real alternatives in stock at all. Not even the evaluation boards for the MicroFC I think. The AFBR from Broadcom still has plenty of stock, though, so it's a good replacement if you can solder it 👍🏻

**Comment by AndreiUlmeyda** [comment]
Wow, that is very nice! Thank you very much. It drastically improves my chance of success. I will probably try a makeshift hotplate for the BGA stuff. I will order the board right away. Have a very nice day, sir.

**Comment by Phoenix1747** [comment]
Somewhat off-topic, but a new batch of MICROFC-60035-SMT SiPMs just arrived at Mouser.

https://eu.mouser.com/ProductDetail/onsemi/MICROFC-60035-SMT-TR1?qs=byeeYqUIh0MxSRIaBcfS6g%3D%3D

Will remove this post again as soon as it sold out, so that the thread stays on topic.

**Comment by Phoenix1747** [comment]
I think I'll close this issue for now. To sum everything up:

There are two different SiPM series you can use at the moment:

- https://eu.mouser.com/ProductDetail/Broadcom-Avago/AFBR-S4N66C013?qs=T3oQrply3y%252B9kiyudO%2F1CA%3D%3D
- https://eu.mouser.com/ProductDetail/onsemi/MICROFC-60035-SMT-TR1?qs=byeeYqUIh0MxSRIaBcfS6g%3D%3D

These sensor series feature multiple different sizes, like 6mm, 4mm, 3mm, ... which you can all use.
Here are breakout boards for the two 6mm versions:

- https://github.com/Open-Gamma-Project/AFBR-SiPM-Carrier-Board
- https://github.com/Open-Gamma-Project/MicroFC-SiPM-Carrier-Board

If you find any other SiPM that supports the 30 V range, go for it! That's really the only, most important requirement.

However, the market for this is really small, obviously. So there aren't many different types of SiPMs at your average electronics distributor like Mouser or Digikey, especially the large 6mm versions. If you find another sensor that should be used, please contact me!
