### ISSUE TITLE
R4 Missing in BOM file

### ISSUE THREAD

**Issue by AndreiUlmeyda** [Open-Gamma-Project/Open-Gamma-Detector#15]
Hey there, I am slowly progressing and am currently searching for R4.
It does not seem to be contained in the current BOM file.
Any tips on what I'm missing?

Since the other resistors number in the hundreds due to the minimum order quantity, there should be one I already have which can be used.

Cheers!

**Comment by Phoenix1747** [comment]
Yes, that's a deliberate choice, it's an optional part. For low energies (<50 keV) I sometimes have a problem with the output voltage swing of the preamp and to mitigate that you can solder in R4 which will then raise the input voltage and therefore the output so that the signal is above the inherent swing of the op amp. This way you can read lower energies (voltages) for a fixed gain up to the SiPM noise.

But due to the preamp as well as SiPM gain being variable now and this voltage divider also introducing some noise into the signal I opted to leave this part out. If you want to play around with it and see what you can do, you can still solder the resistor that's why I left the pads for it.

**Comment by AndreiUlmeyda** [comment]
Oh, yeah, thanks for the clarification. I read about the optional parts on the underside of the board but neglected this one.

**Comment by Phoenix1747** [comment]
> I read about the optional parts on the underside of the board but neglected this one.

I just added it to the README ;) 106ad5de766cc2003750c1cc0018b859cd8c2e6b
