### ISSUE TITLE
About amplification ratio

### ISSUE THREAD

**Issue by petrichor-m** [Open-Gamma-Project/Open-Gamma-Detector#7]
Hi!That is a great project!Thanks for sharing!
I noticed that the amplification ratio of SIPM signal in the circuit diagram is 300. Is that so? I also use the same SIPM (the bias voltage is 30V), but I will get a lot of dark counts at such a high amplification ratio. Is there a problem with my SIPM.
In addition, I want to know what R7 R16 does. Is it to add a bias voltage to the SIPM signal?
Thank you!

**Comment by Phoenix1747** [comment]
> I noticed that the amplification ratio of SIPM signal in the circuit diagram is 300. Is that so?

No, the three 1k resistors are actually in parallel, so it's actually only 330 Ohms or a gain of ~34. I already know about the fixed gain issues, though. It's getting fixed in the next board revision!

> In addition, I want to know what R7 R16 does. Is it to add a bias voltage to the SIPM signal?

R16 is the recommended resistor value for this SiPM's readout. It's there to create a voltage drop with the current that the SiPM produces. R7 just raises the voltage at the op amp input (resistor divider) so that the tiny SiPM pulses get over the output swing of the amp.

**Comment by petrichor-m** [comment]
Oh,I made a terrible misttake.For some reason I thought the resistors were in series.I shouldn't have.Thank you for you reply!
